In [ ]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from random import randrange
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt

data_test = pd.read_csv("/content/IPL_test.csv")
data_train=pd.read_csv("/content/IPL_train.csv")


enc = OneHotEncoder(dtype = float)
overs = [[i] for i in range(1, 21)]
enc.fit(overs)

def drop_feature(df):
    return df.drop(["batting_team", "ball", "bowler",
                    "batsman", "dismissal_kind", "fielder",
                    "bowling_team", "non_striker"
                    ], axis = 1)
test = drop_feature(data_test)
train=drop_feature(data_train)


In [ ]:
#Test Data
matchid=124
cum_run=[]
m=[]
sum=0
count=1
for i in range(len(test)):
  if test['match_id'][i]!=matchid:
    matchid=test['match_id'][i]
    try:
      sum=test['total_runs'][i]
      count=1
    except:
      continue
    cum_run.append(sum)
    m.append(count)
  else:
    sum+=test['total_runs'][i]
    count+=1
    cum_run.append(sum)
    m.append(count)
test['cum_run']=cum_run
test['balls']=m
test

match_id  over  wide_runs  bye_runs  legbye_runs  noball_runs  \
0          124     1          0         0            0            0   
1          124     1          0         0            0            0   
2          124     1          0         0            0            0   
3          124     1          0         0            0            0   
4          124     1          0         0            0            0   
...        ...   ...        ...       ...          ...          ...   
6142       304     8          0         0            0            0   
6143       304     8          0         0            1            0   
6144       304     8          0         0            0            0   
6145       304     8          0         0            0            0   
6146       304     9          0         0            0            0   

      penalty_runs  batsman_runs  extra_runs  total_runs player_dismissed  \
0                0             0           0           0              NaN   
1                0             4           0           4              NaN   
2                0             4           0           4              NaN   
3                0             4           0           4              NaN   
4                0             0           0           0              NaN   
...            ...           ...         ...         ...              ...   
6142             0             0           0           0              NaN   
6143             0             0           1           1              NaN   
6144             0             2           0           2              NaN   
6145             0             4           0           4              NaN   
6146             0             1           0           1              NaN   

      cum_run  balls  
0           0      2  
1           4      3  
2           8      4  
3          12      5  
4          12      6  
...       ...    ...  
6142       53     49  
6143       54     50  
6144       56     51  
6145       60     52  
6146       61     53  

[6147 rows x 13 columns]

In [ ]:
from numpy import NaN
matchid=1
cum_run=[]
m=[]
runrate=[]
wickets=[]
sum_list=[]
sum=0
count=1
len_calc=0
run_counter=0
wicket_counter=0
len_inp=randrange(48,60)
var=0
len_list=[]
for i in range(len(train)):
  if len_calc<len_inp and var==0:
    len_calc+=1
    run_counter+=train['total_runs'][i]
    if type(train['player_dismissed'][i])==str:
      wicket_counter+=1
  if len_calc==len_inp:
    len_calc=0
    len_list.append(len_inp)
    len_inp=randrange(48,60)
    wickets.append(wicket_counter)
    runrate.append(6*run_counter/count)
    wicket_counter=0
    run_counter=0
    var=1
  if train['match_id'][i]!=matchid:
    var=0
    matchid=train['match_id'][i]
    sum_list.append(sum)
    try:
      sum=train['total_runs'][i]
      count=1
    except:
      continue
    cum_run.append(sum)
    m.append(count)
  else:
    sum+=train['total_runs'][i]
    count+=1
    cum_run.append(sum)
    m.append(count)
sum_list.append(sum)
train['cum_run']=cum_run
train['balls']=m
len(sum_list),len(wickets),len(runrate),len(len_list)

(300, 300, 300, 300)

In [ ]:
df=pd.DataFrame()
df['Balls']=len_list
df['wickets']=wickets
df['runrate']=runrate

In [ ]:
df

Balls  wickets   runrate
0       49        1  9.061224
1       58        3  8.068966
2       53        3  7.471698
3       48        3  4.125000
4       50        0  6.720000
..     ...      ...       ...
295     53        2  7.132075
296     54        2  7.333333
297     51        1  6.470588
298     52        2  6.000000
299     59        1  9.762712

[300 rows x 3 columns]

In [ ]:
feature=df.to_numpy()
label=[]
for i in range(len(sum_list)):
  label.append([sum_list[i]])
print(feature,label)

[[49.          1.          9.06122449]
 [58.          3.          8.06896552]
 [53.          3.          7.47169811]
 [48.          3.          4.125     ]
 [50.          0.          6.72      ]
 [53.          2.          7.35849057]
 [56.          2.          7.5       ]
 [49.          1.          5.14285714]
 [51.          0.          9.05882353]
 [56.          1.          7.71428571]
 [55.          4.          6.54545455]
 [51.          1.          8.70588235]
 [53.          0.          8.1509434 ]
 [58.          4.          6.20689655]
 [58.          0.         11.06896552]
 [52.          2.          7.15384615]
 [52.          4.          6.34615385]
 [53.          0.         10.98113208]
 [52.          2.          8.42307692]
 [51.          3.          6.35294118]
 [48.          2.          9.25      ]
 [53.          3.          5.88679245]
 [57.          2.          5.15789474]
 [51.          3.          5.29411765]
 [50.          2.          9.24      ]
 [57.          0.        

In [ ]:
model=DecisionTreeRegressor(max_depth=15)
model.fit(feature,label)

DecisionTreeRegressor(max_depth=15)

In [ ]:
matchid=124
wicket_list=[]
ball_list=[]
wicket_counter=0
m=[]
id=[matchid]
for i in range(len(test)):
  if type(test['player_dismissed'][i])==str:
    wicket_counter+=1
  if matchid!=test['match_id'][i]:
    wicket_list.append(wicket_counter)
    eminem=wicket_counter
    wicket_counter=0
    ball_list.append(test['balls'][i-1])
    matchid=test['match_id'][i]
    m.append(6*test['cum_run'][i-1]/test['balls'][i-1])
    id.append(matchid)
wicket_list.append(eminem)
ball_list.append(test['balls'][i])
m.append(6*test['cum_run'][len(test)-2]/test['balls'][len(test)-2])
len(m),len(wicket_list),len(ball_list)

(100, 100, 100)

In [ ]:
test

match_id  over  wide_runs  bye_runs  legbye_runs  noball_runs  \
0          124     1          0         0            0            0   
1          124     1          0         0            0            0   
2          124     1          0         0            0            0   
3          124     1          0         0            0            0   
4          124     1          0         0            0            0   
...        ...   ...        ...       ...          ...          ...   
6142       304     8          0         0            0            0   
6143       304     8          0         0            1            0   
6144       304     8          0         0            0            0   
6145       304     8          0         0            0            0   
6146       304     9          0         0            0            0   

      penalty_runs  batsman_runs  extra_runs  total_runs player_dismissed  \
0                0             0           0           0              NaN   
1                0             4           0           4              NaN   
2                0             4           0           4              NaN   
3                0             4           0           4              NaN   
4                0             0           0           0              NaN   
...            ...           ...         ...         ...              ...   
6142             0             0           0           0              NaN   
6143             0             0           1           1              NaN   
6144             0             2           0           2              NaN   
6145             0             4           0           4              NaN   
6146             0             1           0           1              NaN   

      cum_run  balls  
0           0      2  
1           4      3  
2           8      4  
3          12      5  
4          12      6  
...       ...    ...  
6142       53     49  
6143       54     50  
6144       56     51  
6145       60     52  
6146       61     53  

[6147 rows x 13 columns]

In [ ]:
df2=pd.DataFrame()
df2['Balls']=ball_list
df2['wickets']=wicket_list
df2['runrate']=m
df2

Balls  wickets   runrate
0      52        2  8.538462
1      52        1  6.923077
2      51        3  7.529412
3      58        2  7.137931
4      74        2  8.027027
..    ...      ...       ...
95     66        0  8.363636
96     52        3  5.538462
97     55        2  7.200000
98     65        2  5.630769
99     53        2  6.923077

[100 rows x 3 columns]

In [ ]:
feat=df2.to_numpy()

In [ ]:
predictor=model.predict(feat)

In [ ]:
predictor=predictor.astype(np.int32)

In [ ]:
predictor

array([104, 182, 132, 125, 163, 118, 118, 116, 174,  89, 149, 125, 175,
       114, 175, 208, 139, 149, 208, 166,  67, 118, 163, 118, 136, 168,
       191, 162, 191, 113, 226, 213, 177, 169, 222, 134, 163, 175, 178,
       214, 188, 149, 170, 118, 191, 134, 143, 136, 125, 187, 150, 184,
       168, 114, 147, 134, 177, 183, 116, 185, 163, 209, 209, 134, 158,
       149, 149, 163, 212, 168, 169, 134, 169, 168,  95, 235, 163, 133,
       183, 163, 147, 141, 149, 168, 129, 164, 152, 182, 114, 190, 149,
       169, 149, 191, 212, 191, 161, 154, 136, 165], dtype=int32)

In [ ]:
result=pd.DataFrame()

In [ ]:
result['match_id']=id
result['prediction']=predictor

In [ ]:
result.to_csv('mnq.csv')

In [ ]:
result

match_id  prediction
0        124       104.0
1        592       182.5
2        630       132.0
3        188       125.0
4        287       163.0
..       ...         ...
95       300       191.0
96       270       161.0
97       179       154.0
98       504       136.5
99       304       165.0

[100 rows x 2 columns]

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
def Predict(trainfile,testfile):
  data_test = pd.read_csv(testfile)
  enc = OneHotEncoder(dtype = float)
  overs = [[i] for i in range(1, 21)]
  enc.fit(overs)
  def drop_feature(df):
      return df.drop(["batting_team", "ball", "bowler",
                      "batsman", "dismissal_kind", "player_dismissed", "fielder",
                      "bowling_team", "non_striker"
                      ], axis = 1)
  test = drop_feature(data_test)
  matchid=124
  cum_run=[]
  m=[]
  sum=0
  count=1
  for i in range(len(test)):
    if test['match_id'][i]!=matchid:
      matchid=test['match_id'][i]
      try:
        sum=test['total_runs'][i]
        count=1
      except:
        continue
      cum_run.append(sum)
      m.append(count)
    else:
      sum+=test['total_runs'][i]
      count+=1
      cum_run.append(sum)
      m.append(count)
  test['cum_run']=cum_run
  test['balls']=m
  matchid=124
  m=[]
  id=[matchid]
  for i in range(len(test)):
    if matchid!=test['match_id'][i]:
      matchid=test['match_id'][i]
      m.append(20*6.4*test['cum_run'][i-1]/test['balls'][i-1])
      id.append(matchid)
  m.append(20*6.4*test['cum_run'][len(test)-2]/test['balls'][len(test)-2])
  result=pd.DataFrame()
  result['match_id']=id
  result['prediction']=m
  result.to_csv('predicted.csv')